import { Mail } from "lucide-react";
import Image from "next/image";

import {
  InstagramIcon,
  LinkedinIcon,
  TwitterIcon,
} from "@/components/layout/social-icons";
import { RevealWrapper } from "@/components/motion/reveal-wrapper";
import { Container, Heading, Paragraph } from "@/components/ui";
import { siteConfig } from "@/lib/site-config";

/**
 * TeamGrid — placeholder roster: names, titles, and focus lines, at the
 * client's own direction, pending the real team's details.
 *
 * Avatars are illustrated portraits generated by DiceBear's "notionists"
 * style (see `next.config.ts` for the remote-image allowlist entry), keyed
 * to each name as a stable seed — the same person always renders the same
 * illustration. Deliberately not a photo, real or synthetic: nothing here
 * should read as an actual photograph of a specific real person who was
 * never asked. Swap the array below for the real roster (photos included,
 * if the client provides them) once it's confirmed.
 */
const TEAM = [
  {
    name: "Marcus Tan",
    title: "Founder & Managing Director",
    focus: "Sets the engineering standard every repair is held to.",
  },
  {
    name: "Wei Ling Ong",
    title: "Lead Battery Engineer",
    focus: "Cell-level diagnostics and thermal management systems.",
  },
  {
    name: "Rajesh Kumar",
    title: "Diagnostics & Testing Specialist",
    focus: "Verifies every repair against GB 38031-2020 tolerances.",
  },
  {
    name: "Sarah Lim",
    title: "Component Repair Technician",
    focus: "Cell, busbar, and BMS-level repair work on the bench.",
  },
  {
    name: "Daniel Ng",
    title: "Client Relations Manager",
    focus: "The first call for fleet, dealership, and corporate accounts.",
  },
  {
    name: "Priya Nair",
    title: "Operations Manager",
    focus: "Keeps islandwide assessments and servicing on schedule.",
  },
] as const;

function avatarUrl(name: string) {
  const seed = encodeURIComponent(name);
  return `https://api.dicebear.com/9.x/notionists/png?seed=${seed}&backgroundColor=f1f2f5&size=480`;
}

export function TeamGrid() {
  return (
    <section className="bg-void relative py-16 lg:py-28">
      <div
        aria-hidden="true"
        className="bg-ion/15 pointer-events-none absolute top-1/2 left-1/2 h-[36rem] w-[36rem] -translate-x-1/2 -translate-y-1/2 rounded-full blur-[140px]"
      />

      <Container className="relative z-10 flex flex-col items-center gap-10 lg:gap-16">
        <div className="flex max-w-2xl flex-col items-center gap-4 text-center">
          <RevealWrapper variant="fade">
            <span className="text-ion text-label-sm font-mono">The Roster</span>
          </RevealWrapper>
          <RevealWrapper variant="blur" delay={0.1} duration={1}>
            <Heading as="h2" size="h2" className="uppercase">
              The People Behind The Work
            </Heading>
          </RevealWrapper>
          <RevealWrapper variant="fade" delay={0.2}>
            <Paragraph size="body" className="max-w-xl text-balance">
              Every enquiry reaches someone on this list directly — not a
              call centre.
            </Paragraph>
          </RevealWrapper>
        </div>

        <div className="grid w-full grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4 lg:gap-6">
          {TEAM.map((member, index) => {
            const mailtoHref = `mailto:${siteConfig.contactEmail}?subject=${encodeURIComponent(
              `For the attention of ${member.name}`,
            )}`;

            return (
              <RevealWrapper
                key={member.name}
                variant="blur"
                delay={index * 0.08}
                duration={0.7}
                className="h-full"
              >
                <div className="border-border bg-graphite/60 hover:border-ion/50 ease-engineered flex h-full flex-col overflow-hidden rounded-md border transition-colors duration-300">
                  <div className="bg-graphite-light relative aspect-[4/5] w-full">
                    <Image
                      src={avatarUrl(member.name)}
                      alt={`Illustrated placeholder portrait for ${member.name}`}
                      fill
                      sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw"
                      className="object-cover"
                    />
                  </div>

                  <div className="flex flex-1 flex-col items-center gap-3 p-6 text-center">
                    <div className="flex flex-col gap-1">
                      <span className="font-display text-h4 text-foreground">
                        {member.name}
                      </span>
                      <span className="text-ion text-label-sm font-mono">{member.title}</span>
                    </div>

                    <p className="font-body text-muted text-sm leading-relaxed">
                      {member.focus}
                    </p>

                    <div className="mt-auto flex items-center gap-2 pt-2">
                      <a
                        href="#"
                        aria-label={`${member.name} on LinkedIn`}
                        className="border-border text-muted ease-engineered hover:border-ion/60 hover:text-ion flex h-9 w-9 items-center justify-center rounded-full border transition-all duration-300 hover:scale-105"
                      >
                        <LinkedinIcon className="h-4 w-4" />
                      </a>
                      <a
                        href="#"
                        aria-label={`${member.name} on Twitter`}
                        className="border-border text-muted ease-engineered hover:border-ion/60 hover:text-ion flex h-9 w-9 items-center justify-center rounded-full border transition-all duration-300 hover:scale-105"
                      >
                        <TwitterIcon className="h-4 w-4" />
                      </a>
                      <a
                        href="#"
                        aria-label={`${member.name} on Instagram`}
                        className="border-border text-muted ease-engineered hover:border-ion/60 hover:text-ion flex h-9 w-9 items-center justify-center rounded-full border transition-all duration-300 hover:scale-105"
                      >
                        <InstagramIcon className="h-4 w-4" />
                      </a>
                      <a
                        href={mailtoHref}
                        aria-label={`Email ${siteConfig.name} for ${member.name}`}
                        className="border-border text-muted ease-engineered hover:border-ion/60 hover:text-ion flex h-9 w-9 items-center justify-center rounded-full border transition-all duration-300 hover:scale-105"
                      >
                        <Mail className="h-4 w-4" strokeWidth={1.5} />
                      </a>
                    </div>
                  </div>
                </div>
              </RevealWrapper>
            );
          })}
        </div>
      </Container>
    </section>
  );
}
